# Generated by Django 4.1.4 on 2023-02-13 15:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=50)),
                ('cuerpo', ckeditor.fields.RichTextField()),
                ('autor', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('imagen', models.ImageField(upload_to='../media/imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('tipo', models.IntegerField(choices=[(1, 'Vegetariano'), (2, 'Vegano'), (3, 'Con carne'), (4, 'Free Gluten')])),
                ('tiempo', models.IntegerField()),
                ('dificultad', models.IntegerField(choices=[(1, 'Facil'), (2, 'Media'), (3, 'Dificil')])),
                ('ingredientes', ckeditor.fields.RichTextField()),
                ('instrucciones', ckeditor.fields.RichTextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(upload_to='../media/imagenes/')),
            ],
        ),
    ]
