# Generated by Django 4.1.7 on 2023-02-15 22:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alter_blog_imagen_alter_recetas_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='resumen',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Vegetariano'), (2, 'Vegano'), (3, 'Contiene carne'), (4, 'Free Gluten')]),
        ),
    ]
